Script to refund successful late fees or cancel the pending late fee payment for refunded orders.
Laybuy/laybuy-order-refunds-script pull request #1
Opened 2021-12-07 01:48 UTC by vaimor-LB

[sc-11432]

The cancellation or refund of the late fees should be reflected in the customer tables + on Manage

Please note, there may be multiple late fees on the order (all late fees on the order need to be cancelled/refunded)

Things to check...does the script do all the required work on the following platform db tables:

- Customer
- Order
- Refund
- Payment

2021-12-08 02:42 UTC, BarryDahlberg requested changes
Cool, the basic outline is there, just some tweaks to the logic and output.

2021-12-08 02:42 UTC, BarryDahlberg commented on OrderRefundsScript/RunService.cs
> +                        await Task.Run(() => RefundOrderAsync(order.PaymentIntent, payment));
Is there any reason for the `Task.Run` here? Why not just `await RefundOrderAsync(...` directly rather than blocking a new thread?

2021-12-08 02:42 UTC, BarryDahlberg commented on OrderRefundsScript/RunService.cs
> +            await _platformDbContext.SaveChangesAsync();
I'd probably call `SaveChangesAsync` inside your loop as it means you are much less likely to lose work in progress if the whole scrip does not complete. That way you'll commit to DB after each call to Stripe.

2021-12-08 02:42 UTC, BarryDahlberg commented on OrderRefundsScript/RunService.cs
> +                    continue;
Does this mean there was an error in the original export? Or something has changed since I guess. Would be good to record this so we know.

2021-12-08 02:42 UTC, BarryDahlberg commented on OrderRefundsScript/RunService.cs
> +            payment.Error = NoteForUpdatedPayments;
I'm a bit wary of using a column titled "Error" for notes when we're not in an error case. Please have a look at the `note` table which can be used to record general notes against the order ID.

2021-12-08 02:42 UTC, BarryDahlberg commented on OrderRefundsScript/RunService.cs
> +                Time = DateTime.Now.TimeOfDay
For platform DB please check this does in as NZ time. The other DBs are generally UTC but platform is on New Zealand time :(

2021-12-08 02:42 UTC, BarryDahlberg commented on OrderRefundsScript/RunService.cs
> +            payment.Status = PaymentStatusCanceled;
Cna you make the entry to the `note` table common so these orders get it too please?

2021-12-08 02:42 UTC, BarryDahlberg commented on OrderRefundsScript/RunService.cs
> +                Amount = (long) ((payment.Amount ?? 0) * 100),
Error if 0?

2021-12-08 02:42 UTC, BarryDahlberg commented on OrderRefundsScript/Program.cs
> +            Log.Logger.Information("Starting Script");
You have set up the logger nicely but don't seem to have actually logged the outcome of each order. Please add enough logs so we can see afterwards what the script did and compare notes.

2021-12-08 02:42 UTC, BarryDahlberg commented on OrderRefundsScript/RunService.cs
> +                        break;
Probably want a `case already cancelled:`  here and log it. That will give you the ability to confidently re-run the script if it fails part way through, and know why it's not doing anything.

2021-12-08 02:42 UTC, BarryDahlberg commented on OrderRefundsScript/RunService.cs
> +                return;
Log all the things :)

2021-12-08 08:36 UTC, vaimor-LB commented on OrderRefundsScript/RunService.cs
> +            await _platformDbContext.SaveChangesAsync();
Yes thank you, was not sure whether it was right to have it inside the loop in terms of optimal performance

2021-12-08 08:59 UTC, vaimor-LB commented on OrderRefundsScript/RunService.cs
> +                    continue;
Yeap good idea 👍

2021-12-08 10:22 UTC, vaimor-LB commented on OrderRefundsScript/RunService.cs
> +            payment.Error = NoteForUpdatedPayments;
Updated 👍

2021-12-08 10:22 UTC, vaimor-LB commented on OrderRefundsScript/RunService.cs
> +                Time = DateTime.Now.TimeOfDay
Changed code to use local time 😄

2021-12-08 10:23 UTC, vaimor-LB commented on OrderRefundsScript/RunService.cs
> +            payment.Status = PaymentStatusCanceled;
Yes done, new entry created for cancelling and refunding orders 😄

2021-12-08 21:13 UTC, vaimor-LB commented on OrderRefundsScript/RunService.cs
> +                return;
Yeap agreed

2021-12-08 21:30 UTC, vaimor-LB commented on OrderRefundsScript/Program.cs
> +            Log.Logger.Information("Starting Script");
Done, went for overkill this time! 😈

2021-12-08 22:10 UTC, vaimor-LB commented on OrderRefundsScript/RunService.cs
> +                        break;
Great idea! 🙏

2021-12-08 22:21 UTC, vaimor-LB commented on OrderRefundsScript/RunService.cs
> +                Amount = (long) ((payment.Amount ?? 0) * 100),
Yes added logic to handle 0 amount 😓

2021-12-09 03:17 UTC, BarryDahlberg commented on OrderRefundsScript/RunService.cs
> +            payment.Type = PaymentTypeRefund;
I think this needs to stay as payment type PENATLY, otherwise it's going to throw the order total out?

2021-12-09 03:57 UTC, BarryDahlberg approved these changes

2022-01-04 21:10 UTC, merged